#!/bin/bash
echo "HOSTS:"
cat /etc/hosts
echo "MKFS..."
mkfs.xtreemfs -m 777 -a NULL xtreemfsmrc/openolympus 

echo "MOUNTING..."
mount.xtreemfs xtreemfsdir/openolympus /opt/openolympus/storage 
echo "MOUNTED"
xtfsutil /opt/openolympus/storage
cd /opt/openolympus/

echo "STARTING WEB SERVER"
/usr/bin/java -jar -Dlogging.file=/var/log/openolympus.log -Djppf.config=/opt/openolympus/jppf.properties /opt/openolympus/openolympus.jar
